Repository chill-viking/ng-libs, pull requests merged in 2023-03, with the labels that each got.

#127 chore(deps): fix audit results
  package-lock.json
Labels: dependencies :scroll:, non-functional improvement :tada:

#126 chore: release main
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#138 chore(workflows): adjust permissions for CD
  .github/workflows/cd.yml
Labels: non-functional improvement :tada:, security flaw :space_invader:

#139 chore(workflows): use workflows release-manifest-please
  .github/workflows/cd.yml
  .github/workflows/release-please.yml
Labels: non-functional improvement :tada:
